### PR TITLE
Fixed pull request and updated the constants to enam FINANCEHELPER-30

### LINKED ISSUE #10: Add bread crumbs to authorized header
https://mui.com/material-ui/react-breadcrumbs/#integration-with-react-router

### PR DESCRIPTION
**Pull request by officer04**

### CODE REVIEW

File: src/types/shared/http-status-code.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+export const enum HttpStatusCode {
+  "OK" = 200,
+  "BAD_REQUEST" = 400,
+  "UN_AUTHORIZATION" = 401,
```
Comment (egor4yt) [inline src/types/shared/http-status-code.ts]: UNAUTHORIZED

**Review by egor4yt — CHANGES_REQUESTED** [review]

**Review by egor4yt — APPROVED** [review]
